package girard.sc.expt.io.msg;

import girard.sc.expt.sql.NewExptOutputReq;
import girard.sc.wl.io.WLGeneralServerConnection;
import girard.sc.wl.io.msg.WLMessage;

/**
 * Sets up an entry in the database for the experiment that is being started.  The
 * ID given by the database is then used to keep track of all files generated by
 * the experiment that are to be saved to the database.
 *
 * @author Dudley Girard
 * @version ExNet III 3.4
 * @since JDK1.1
 */

public class NewExptOutputReqMsg extends ExptMessage 
    { 
    public NewExptOutputReqMsg (Object args[])
        {
        super(args);
        }

    public WLMessage getGeneralServerResponse(WLGeneralServerConnection wlgsc)
        {
        Object[] args = this.getArgs();

        if (!(args[0] instanceof String) || !(args[1] instanceof String))
            {
            // Return an error msg.
            Object[] err_args = new Object[2];
            err_args[0] = new String("Incorrect Object Types1 - NewExptOutputReqMsg");
            err_args[1] = new String("NewExptOutputReqMsg");
            return new ExptErrorMsg(err_args);
            }

        Object[] data = new Object[6];
        data[0] = args[0];
        data[1] = args[1];
        data[2] = args[2];
        data[3] = args[3];
        data[4] = args[4];

        NewExptOutputReq tmp = new NewExptOutputReq(data,wlgsc,this);
	System.err.println(" in the getGeneralResponse Method of NewExptOutputReqMsg"); 
        if (tmp.runUpdate())
            {
            Object[] out_args = new Object[1];
            out_args[0] = data[5];
            return new NewExptOutputReqMsg(out_args);
            }
        else
            {
            Object[] err_args = new Object[2];
            err_args[0] = new String("Exception Error - NewExptOutputReqMsg");
            err_args[1] = new String("NewExptOutputReqMsg");
            return new ExptErrorMsg(err_args);
            }
        }
    }
